import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import Header from '../components/Header';
import Feed from '../components/Feed';
import Modal  from '../components/Modal';

const Home: NextPage = () => {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Instagram Clone created by Gabriel Clemente</title>
        <meta name="Instagram Clone by Gabriel Clemente" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {Header} */}
        <Header/>
      {/* {Feed} */}
        <Feed /> 
      {/* {Modal} */}
        <Modal />
    </div>
  )
}

export default Home;
